**Week 2 Discussion Section: Water Conflicts in the Colorado River Basin**

Where was the data collected from? This data was collected from the USGS Science Data Catalog.

During what time frame were the observations in the dataset collected? The observations were collected from from 2005 to 2021.

What was the author’s perceived value of this dataset? The author's percieved value of this dataset was to understand social vulnerability to water insecurity, resiliency demonstrated by institutions, and conflict or crisis around water resource management.

Citation: Holloman, D.V., Hines, M.K., and Zoanni, D.K., 2023, Coded Water Conflict and Crisis Events in the Colorado River Basin, Derived from LexisNexis search 2005-2021: U.S. Geological Survey data release, https://doi.org/10.5066/P9X6WR7J.

Date of Access: 10/7/26

Link: [https://www.sciencebase.gov/catalog/item/63acac09d34e92aad3ca1480](https://www.sciencebase.gov/catalog/item/63acac09d34e92aad3ca1480)

In [3]:
# Import pandas
import pandas as pd

# Read data
df = pd.read_csv("data/Colorado River Basin Water Conflict Table.csv")

In [4]:
# Display columns
df.columns

Index(['Event', 'Search Source', 'Newspaper', 'Article Title', 'Duplicate',
       'Report Date', 'Report Year', 'Event Date', 'Event Day', 'Event Month',
       'Event Year', 'Conflict Present', 'Crisis Present', 'Basin', 'HUC6',
       'HUC2', 'Place', 'County', 'County FIPS', 'State', 'State FIPS',
       'Urban or Rural', 'Issue Type', 'Event Summary', 'Stakeholders',
       'Intensity Value', 'Comments', 'Related Observation Themes',
       'Article Text Search - water quality',
       'Article Text Search - invasive species',
       'Article Text Search - conservation', 'Article Text Search - drought',
       'Article Text Search - flood',
       'Article Text Search - ground water depletion',
       'Article Text Search - depletion',
       'Article Text Search - infrastructure',
       'Article Text Search - fish passage',
       'Article Text Search - instream water rights',
       'Article Text Search - water rights',
       'Article Text Search - intergovernmental',
       'Article Text Search - water transfers',
       'Article Text Search - navigation', 'Article Text Search - fish',
       'Article Text Search - invasive', 'Article Text Search - diversion',
       'Article Text Search - water diversion',
       'Article Text Search - instream', 'Article Text Search - aquatic'],
      dtype='object')

In [6]:
# First three rows
df.head(3)

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,...,12,0,0,0,1,0,0,0,12,1

In [7]:
# Last three rows
df.tail(3)

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,...,2,0,0,0,0,0,0,0,0,0
266,267,USGS301-350.docx,The Salt Lake Tribune,Scientists want to flush water past Glen Canyo...,False,13-Dec-07,2007.0,12,NaN,12.0,...,0,0,0,0,0,2,0,0,0,0
267,268,USGS301-350.docx,Casa Grande Dispatch (AZ),Arizona plan could devastate Pinal farmers,NaN,2-Feb-19,2019.0,1/31/2019,31.0,1.0,...,2,0,0,0,0,0,0,0,0,0

In [8]:
# Number of rows and columns
df.shape

(268, 48)

In [10]:
# Number of unique values
df.nunique()

Event                                           268
Search Source                                     6
Newspaper                                        45
Article Title                                   267
Duplicate                                         2
Report Date                                     235
Report Year                                      18
Event Date                                       52
Event Day                                        12
Event Month                                      12
Event Year                                       21
Conflict Present                                  2
Crisis Present                                    2
Basin                                            25
HUC6                                             22
HUC2                                              7
Place                                           135
County                                            3
County FIPS                                       3
State                                            23
State FIPS                                       19
Urban or Rural                                    6
Issue Type                                       19
Event Summary                                   253
Stakeholders                                    199
Intensity Value                                  10
Comments                                        184
Related Observation Themes                       21
Article Text Search - water quality              10
Article Text Search - invasive species            2
Article Text Search - conservation               15
Article Text Search - drought                    19
Article Text Search - flood                      10
Article Text Search - ground water depletion      1
Article Text Search - depletion                   2
Article Text Search - infrastructure              9
Article Text Search - fish passage                1
Article Text Search - instream water rights       1
Article Text Search - water rights               17
Article Text Search - intergovernmental           2
Article Text Search - water transfers             2
Article Text Search - navigation                  2
Article Text Search - fish                        8
Article Text Search - invasive                    3
Article Text Search - diversion                   6
Article Text Search - water diversion             2
Article Text Search - instream                    5
Article Text Search - aquatic                     5
dtype: int64